mode: development
media_root: media
media_url: /media
base_url: /

# add thine plugins
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.urls.UrlCleanerPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
    - hyde.ext.plugins.less.LessCSSPlugin
    - tagger.TaggerPlugin # adds some slugification for humanoid tags
    - slugify.SlugifyPlugin # access the slugify filter from templates

# quit trying to parse funky .js files
simple_copy:
    - media/js/*.js

# context data
#context:
#    data:

# lessCSS
less:
    app:/usr/bin/lessc

# tweak markdown
markdown:
    extensions:
#       - codehilite
        - extra

# default metadata
meta:
    nodemeta: meta.yaml
    created: !!timestamp 2012-02-02 00:00:00
    author: Brian Boucheron

# clean urls please
urlcleaner:
    index_file_names:
        - index.html
    strip_extensions:
        - html
        - xml
    append_slash: true

# define a time-based sorter
sorter:
    time:
        attr:
            - meta.created
        reverse: true
        filters:
            source.kind: html
            meta.listable: true

# set up tag archive generation
tagger:
    sorter: time
    archives:
        blog:
            source: brian
            target: brian/tag
            template: listing.j2
            archive_extension: html
            meta.listable: false

# publish up to github
publisher:
    github:
        type: hyde.ext.publishers.dvcs.Git
        path: ../beardicus.github.com
        url: git@github.com:beardicus/beardicus.github.com.git
        mode: production
